### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by BorisVer** [tiaineno/RateMyDemo#1]
Sovellusta ei saa käynnistymään, ensinäkin schema.sql tiedoston sisällä 
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name TEXT,
    password TEXT
    data bytea
);
puuttuu pilkku, sekä ei ole olemassa username columnia jota vaaditaan tuossa data.py :6 rivissä. En tiedä onko shema.sql unohdettu päivittää mutta sovellusta ei saa tällä hetkellä mitenkään käyntiin.

**Comment by tiaineno** [comment]
Korjattu!
